spring:
  application:
    name: frontend-app

  # Custom OAuth2 configuration for login page
  oauth2:
    custom-idp:
      client-id: frontend-app
      redirect-uri: http://localhost:8081/oauth2/callback
      scope: basic
      authorization-uri: https://kc.idp.com:8443/realms/IBM/protocol/openid-connect/auth
      token-uri: https://kc.idp.com:8443/realms/IBM/protocol/openid-connect/token

server:
  port: 8081
